# Generated by Django 5.2.7 on 2025-11-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_link_token',
            field=models.UUIDField(blank=True, null=True, verbose_name='Токен для привязки Telegram'),
        ),
        migrations.AddField(
            model_name='user',
            name='token_generated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время генерации токена'),
        ),
    ]
